image: node:16.5.0
pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - yarn install
    - vite build --mode gitlab
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - shared
